Sync partial tree

diff --git a/dot-pairsync b/dot-pairsync
--- a/dot-pairsync
+++ b/dot-pairsync
@@ -15,27 +15,6 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-f="$(readlink -f "$PWD")"
-
-if [ "$f" = / ]; then
-  f=
-fi
-
-r="$(echo "$f" | tr / \\n | tail -n +2 | while read i; do
-  a="$a/$i"
-  echo "$a/.pairsync.remote"
-done | tac | while read i; do
-  if [ -e "$i" ]; then
-    cat "$i"
-    break
-  fi
-done)"
-
-if [ -z "$z" ]; then
-  echo "Remote not found" >&2
-  exit 1
-fi
-
 if ! opts=`getopt -q -o "" -l "pull,push" -- "$@"`; then
   echo "Bad invocation" >&2
   exit 1
@@ -68,6 +47,30 @@ if [ "$pull" = 1 ] && [ "$push" = 1 ]; then
   exit 1
 fi
 
+f="$(readlink -f "$PWD")"
+
+if [ "$f" = / ]; then
+  f=
+fi
+
+i="$f"
+while [ -n "$i" ]; do
+  j="$i/.pairsync.remote"
+
+  if [ -e "$j" ]; then
+    r="$(cat "$j")"
+    s="$(echo "$f" | cut -c"$((${#i}+1))-")"
+    break
+  fi
+
+  i="$(echo "$i" | sed 's,/[^/]*$,,')"
+done
+
+if [ -z "$r" ]; then
+  echo "Remote not found" >&2
+  exit 1
+fi
+
 if [ -e "$f/.pairsync.includes" ]; then
   incl="--include-from=$f/.pairsync.includes"
   excl="--exclude=/*"
@@ -76,10 +79,10 @@ fi
 # - Wildcard in source path avoids assuming top dir is writable.
 # - Wildcard is processed by shell in push from local.
 # - Wildcard is processed by rsync in pull from remote.
-# - Push to /afs is very slow with -g (implied by -a) fo some reason.
+# - Push to /afs is very slow with -g (implied by -a) for some reason.
 
 if [ "$push" = 1 ]; then
-  rsync -a --no-g --no-o --delete "$incl" "$excl" "$f"/* "$r"/
+  rsync -a --no-g --no-o --delete "$incl" "$excl" "$f"/* "$r$s"/
 else
-  rsync -a --no-g --no-o --delete "$incl" "$excl" "$r/*" "$f"/
+  rsync -a --no-g --no-o --delete "$incl" "$excl" "$r$s/*" "$f"/
 fi
